import PySimpleGUI as sg

s = {"size": 5}
b = {"size": 4}
c = {"size": 28, "text_color": "blue"}
r = {"size": 5, "disabled_readonly_background_color": "red", "disabled": True}
t = {"text": "XXXXX", "text_color": "red"}

layout = [[sg.Text('Client'), sg.Combo(["SEGC Carrefour Punaauia", "Carrefour Plaza", "SEGC Carrefour Arue",
                                        "Carrefour Taravao"], k="A2", size=24)]]

layout_tee = [[sg.Text('TAILLES', **c), sg.Text('S', size=4, justification="center"),
               sg.Text('M', size=4, justification="center"),
               sg.Text('L', size=4, justification="center"), sg.Text('XL', **s, justification="center"),
               sg.Text('2XL', **s, justification="center"), sg.Text('3XL', size=4, justification="center")],
              [sg.Text('TEE IVD BLACK', size=28), sg.InputText(**s, k="D2"),
               sg.InputText(**s, k="D3"), sg.InputText(**s, k="D4"),
               sg.InputText(**s, k="D5"), sg.InputText(**s, k="D6"), sg.InputText(**s, k="D7")],
              [sg.Text('TEE IVD FLAG MAPE', size=28), sg.InputText(**s, k="D8"),
               sg.InputText(**s, k="D9"), sg.InputText(**s, k="D10"),
               sg.InputText(**s, k="D11"), sg.InputText(**s, k="D12"), sg.InputText(**s, k="D13")],
              [sg.Text('TEE TO RASTA', size=28), sg.InputText(**s, k="D14"),
               sg.InputText(**s, k="D15"), sg.InputText(**s, k="D16"),
               sg.InputText(**s, k="D17"), sg.InputText(**s, k="D18"), sg.InputText(**s, k="D19")],
              [sg.Text('TEE TO ART TROPICAL', size=28), sg.InputText(size=5, k="D20"),
               sg.InputText(**s, k="D21"), sg.InputText(**s, k="D22"),
               sg.InputText(**s, k="D23"), sg.InputText(**s, k="D24"), sg.InputText(**s, k="D25")],
              [sg.Text('TEE TO FLAG TROPICAL', size=28), sg.InputText(**s, k="D26"),
               sg.InputText(**s, k="D27"), sg.InputText(**s, k="D28"),
               sg.InputText(**s, k="D29"), sg.InputText(**s, k="D30"), sg.InputText(**s, k="D31")],
              [sg.Text('TEE IVD PEOPLE', size=28), sg.InputText(**s, k="D123"),
               sg.InputText(**s, k="D124"), sg.InputText(**s, k="D125"),
               sg.InputText(**s, k="D126"), sg.InputText(**s, key="D127")],
              [sg.Text('TEE IVD COMANDO', size=28), sg.InputText(**s, k="D128"),
               sg.InputText(**s, k="D129"), sg.InputText(**s, k="D172"), sg.InputText(**s, k="D173"),
               sg.InputText(**s, k="D174")],
              [sg.Text('TEE IVD TEAHUPOO', size=28), sg.InputText(**s, k="D130"),
               sg.InputText(**s, k="D131"), sg.InputText(**s, k="D132"),
               sg.InputText(**s, k="D133"), sg.InputText(**s, k="D134"), sg.InputText(**s, k="D175")],
              [sg.Text('TEE IVD RASTA FLAG', size=28), sg.InputText(**s, k="D135"), sg.InputText(**s, k="D176"),
               sg.InputText(**s, k="D177"), sg.InputText(**s, k="D178"), sg.InputText(**s, k="D179")],
              [sg.Text('TEE IVD STREET', size=28), sg.InputText(**s, k="D136"),
               sg.InputText(**s, k="D137"), sg.InputText(**s, k="D180"), sg.InputText(**s, k="D181")],
              [sg.Text('TEE VT FLAG TRASH NEON PINK', size=28), sg.InputText(**s, k="D182"),
               sg.InputText(**s, k="D183"),
               sg.InputText(**s, k="D184"), sg.InputText(**s, k="D185"), sg.InputText(**s, k="D186")],
              ]

layout_bs = [[sg.Text('TAILLES', **c), sg.Text('30', **s), sg.Text('32', **s), sg.Text('34', **s),
              sg.Text('36', **s), sg.Text('38', **b), sg.Text('40', **b), sg.Text('42', **s),
              sg.Text('44', **b), sg.Text('46', **b)],
             [sg.Text('BS IVD RASTA II', size=28), sg.InputText(**s, k="D300"),
              sg.InputText(**s, k="D301"), sg.InputText(**s, k="D302"),
              sg.InputText(**s, k="D303"), sg.InputText(**s, k="D304"), sg.InputText(**s, k="D305"),
              sg.InputText(**s, k="D306"), sg.InputText(**s, k="D307"), sg.InputText(**s, k="D308")],
             [sg.Text('BS IVD MAPE', size=28), sg.InputText(**s, k="D309"),
              sg.InputText(**s, k="D310"), sg.InputText(**s, k="D311"),
              sg.InputText(**s, k="D312"), sg.InputText(**s, k="D313"), sg.InputText(**s, k="D314"),
              sg.InputText(**s, k="D315"), sg.InputText(**s, k="D316"), sg.InputText(**s, k="D317")],
             [sg.Text('BS IVD BIGFLAG', size=28), sg.InputText(**s, k="D318"),
              sg.InputText(**s, k="D319"), sg.InputText(**s, k="D320"),
              sg.InputText(**s, k="D321"), sg.InputText(**s, k="D322"), sg.InputText(**s, k="D323"),
              sg.InputText(**s, k="D324"), sg.InputText(**s, k="D325"), sg.InputText(**s, k="D326")],
             [sg.Text('BS TO ART HIBISCUS', size=28), sg.InputText(**s, k="D72"),
              sg.InputText(**s, k="D73"), sg.InputText(**s, k="D74"),
              sg.InputText(**s, k="D75"), sg.InputText(**s, k="D76"), sg.InputText(**s, k="D77"),
              sg.InputText(**s, k="D78"), sg.InputText(**s, k="D79"), sg.InputText(**s, k="D80")],
             [sg.Text('BS TO ART MONSTERA', size=28), sg.InputText(**s, k="D81"),
              sg.InputText(**s, k="D82"), sg.InputText(**s, k="D83"),
              sg.InputText(**s, k="D84"), sg.InputText(**s, k="D85"), sg.InputText(**s, k="D86"),
              sg.InputText(**s, k="D87"), sg.InputText(**s, k="D88"), sg.InputText(**s, k="D89")],
             [sg.Text('BS TO MONSTERA GOLD', size=28), sg.InputText(**s, k="D90"),
              sg.InputText(**s, k="D91"), sg.InputText(**s, k="D92"),
              sg.InputText(**s, k="D93"), sg.InputText(**s, k="D94"), sg.InputText(**s, k="D95"),
              sg.InputText(**s, k="D96"), sg.InputText(**s, k="D97"), sg.InputText(**s, k="D98")],
             [sg.Text('BS TO ART TROPICAL', size=28), sg.InputText(**s, k="D99"),
              sg.InputText(**s, k="D100"), sg.InputText(**s, k="D101"),
              sg.InputText(**s, k="D102"), sg.InputText(**s, k="D103"), sg.InputText(**s, k="D104"),
              sg.InputText(**s, k="D105"), sg.InputText(**s, k="D106"), sg.InputText(**s, k="D107")],
             [sg.Text('BS TO RASTA', size=28), sg.InputText(**s, k="D108"),
              sg.InputText(**s, k="D109"), sg.InputText(**s, k="D110"),
              sg.InputText(**s, k="D111"), sg.InputText(**s, k="D112"), sg.InputText(**s, k="D113"),
              sg.InputText(**s, k="D114"), sg.InputText(**s, k="D115"), sg.InputText(**s, k="D116")],
             [sg.Text('BS IVD COMANDO', size=28), sg.InputText(**s, k="D224"),
              sg.InputText(**s, k="D225"), sg.InputText(**s, k="D226"),
              sg.InputText(**s, k="D227"), sg.InputText(**s, k="D228"), sg.InputText(**s, k="D229"),
              sg.InputText(**s, k="D230")],
             [sg.Text('BS IVD TEAHUPOO', size=28), sg.InputText(**s, k="D235"),
              sg.InputText(**s, k="D236"), sg.InputText(**s, k="D237"),
              sg.InputText(**s, k="D238"), sg.InputText(**s, k="D239"), sg.Text(**t),
              sg.InputText(**s, k="D240")],
             [sg.Text('BS IVD PEOPLE', size=28), sg.InputText(**s, k="D247"),
              sg.InputText(**s, k="D248"), sg.InputText(**s, k="D249"),
              sg.InputText(**s, k="D250"), sg.InputText(**s, k="D251"), sg.InputText(**s, k="D252")],
             [sg.Text('BS VT ICE GREEN', size=28), sg.InputText(**s, k="D267"),
              sg.InputText(**s, k="D268"), sg.InputText(**s, k="D269"),
              sg.InputText(**s, k="D270"), sg.InputText(**s, k="D271"), sg.InputText(**s, k="D272"),
              sg.InputText(**s, k="D273"), sg.InputText(**s, k="D274")],
             [sg.Text('BS VT PARADISE', size=28), sg.InputText(**s, k="D275"),
              sg.InputText(**s, k="D276"), sg.InputText(**s, k="D277"),
              sg.InputText(**s, k="D278"), sg.InputText(**s, k="D279"), sg.InputText(**s, k="D280"),
              sg.InputText(**s, k="D281"), sg.InputText(**s, k="D282"), sg.InputText(**s, k="D283")],
             [sg.Text('BS VT PAREU APE', size=28), sg.InputText(**s, k="D284"),
              sg.InputText(**s, k="D285"), sg.InputText(**s, k="D286"),
              sg.InputText(**s, k="D287"), sg.InputText(**s, k="D288"), sg.InputText(**s, k="D289"),
              sg.InputText(**s, k="D290")]
             ]

layout_polo = [[sg.Text('TAILLES', **c), sg.Text('S', size=4, justification="center"),
                sg.Text('M', size=4, justification="center"),
                sg.Text('L', size=4, justification="center"), sg.Text('XL', **s, justification="center"),
                sg.Text('2XL', **s, justification="center"), sg.Text('3XL', size=4, justification="center")],
               [sg.Text('POLO TO HIBISCUS BEIGE', size=28), sg.InputText(**s, k="D44"),
                sg.InputText(**s, k="D45"), sg.InputText(**s, k="D46"),
                sg.InputText(**s, k="D47"), sg.InputText(**s, k="D48"), sg.InputText(**s, k="D49")],
               [sg.Text('POLO TO HIBISCUS CORAIL', size=28), sg.InputText(**s, k="D50"),
                sg.InputText(**s, k="D51"), sg.InputText(**s, k="D52"),
                sg.InputText(**s, k="D53"), sg.InputText(**s, k="D54"), sg.InputText(**s, k="D55")],
               [sg.Text('POLO TO HIBISCUS II', size=28), sg.InputText(size=5, k="D56"),
                sg.InputText(**s, k="D57"), sg.InputText(**s, k="D58"),
                sg.InputText(**s, k="D59"), sg.InputText(**s, k="D60"), sg.InputText(**s, k="D61")],
               [sg.Text('POLO VT PAREU APE LIGHT', size=28), sg.InputText(**s, k="D154"),
                sg.InputText(**s, key="D199"), sg.InputText(**s, k="D155"),
                sg.InputText(**s, k="D156"), sg.InputText(**s, k="D157"), sg.InputText(**s, k="D200")],
               [sg.Text('POLO VT PAREU APE BLUE', size=28), sg.InputText(**s, key="D207"),
                sg.InputText(**s, key="D208"), sg.InputText(**s, key="D209"),
                sg.InputText(**s, k="D158"), sg.InputText(**s, k="D159"), sg.InputText(**s, k="D210")],
               [sg.Text('POLO VT PAREU APE PINK', size=28), sg.InputText(**s, k="D160"),
                sg.InputText(**s, k="D161"), sg.InputText(**s, k="D162"),
                sg.InputText(**s, k="D163"), sg.InputText(**s, k="D164"), sg.InputText(**s, k="D211")],
               [sg.Text('POLO VT PAREU APE PURPLE', size=28), sg.InputText(**s, k="D165"),
                sg.InputText(**s, key="D212"),
                sg.InputText(**s, k="D166"), sg.InputText(**s, k="D167"),
                sg.InputText(**s, k="D168"), sg.InputText(**s, k="D169")],
               [sg.Text('POLO VT PAREU APE GREEN', size=28), sg.InputText(**s, k="D170"), sg.InputText(**s, key="D213"),
                sg.InputText(**s, key="D214"), sg.InputText(**s, key="D215"), sg.InputText(**s, k="D171"),
                sg.InputText(**s, key="D216")],
               [sg.Text('POLO VT FREDDY', size=28), sg.InputText(size=5, k="D187"),
                sg.InputText(**s, k="D188"), sg.InputText(**s, k="D189"),
                sg.InputText(**s, k="D190"), sg.InputText(**s, k="D192"), sg.InputText(**s, k="D191")],
               [sg.Text('POLO VT FREDDY 2', size=28), sg.InputText(size=5, k="D201"),
                sg.InputText(**s, k="D202"), sg.InputText(**s, k="D203"),
                sg.InputText(**s, k="D204"), sg.InputText(**s, k="D205"), sg.InputText(**s, k="D206")],
               [sg.Text('POLO VT PAREU APE', size=28), sg.InputText(size=5, k="D193"),
                sg.InputText(**s, k="D194"), sg.InputText(**s, k="D195"),
                sg.InputText(**s, k="D196"), sg.InputText(**s, k="D197"), sg.InputText(**s, k="D198")]
               ]

layout_deb = [[sg.Text('TAILLES', **c), sg.Text('S', size=4, justification="center"),
               sg.Text('M', size=4, justification="center"),
               sg.Text('L', size=4, justification="center"), sg.Text('XL', **s, justification="center"),
               sg.Text('2XL', **s, justification="center"), sg.Text('3XL', size=4, justification="center")],
              [sg.Text('DEB IVD RASTA', size=28), sg.InputText(size=5, k="D32"),
               sg.InputText(**s, k="D33"), sg.InputText(**s, k="D34"),
               sg.InputText(**s, k="D35"), sg.InputText(**s, k="D36"), sg.InputText(**s, k="D37")],
              [sg.Text('DEB TO RASTA', size=28), sg.InputText(**s, k="D38"),
               sg.InputText(**s, k="D39"), sg.InputText(**s, k="D40"),
               sg.InputText(**s, k="D41"), sg.InputText(**s, k="D42"), sg.InputText(**s, k="D43")],
              [sg.Text('DEB VT FLAG TRASH PINK', size=28), sg.InputText(**s, k="D138"),
               sg.InputText(**s, k="D139"), sg.InputText(**s, k="D140"),
               sg.InputText(**s, k="D141"), sg.InputText(**s, k="D142")],
              [sg.Text('DEB IVD COMANDO', size=28), sg.InputText(**s, k="D143"),
               sg.InputText(**s, k="D144"), sg.InputText(**s, k="D145"), sg.InputText(**s, k="D217"),
               sg.InputText(**s, k="D218")],
              [sg.Text('DEB IVD PEOPLE', size=28), sg.InputText(**s, k="D146"),
               sg.InputText(**s, k="D147"), sg.Text(**t), sg.Text(**t), sg.InputText(**s, k="D148")],
              [sg.Text('DEB VT BLACK SUNSET', size=28), sg.InputText(**s, k="D219"),
               sg.InputText(**s, k="D220"), sg.InputText(**s, k="D221"),
               sg.InputText(**s, k="D222"), sg.InputText(**s, k="D223")]]

layout_cap = [[sg.Text('CASQUETTES', **c), sg.Text('Q', **s)],
              [sg.Text('CAP IVD RASTA', size=28), sg.InputText(**s, k="D297")],
              [sg.Text('CAP IVD MAPE', size=28), sg.InputText(**s, k="D298")],
              [sg.Text('CAP IVD FLAG', size=28), sg.InputText(**s, k="D299")],
              [sg.Text('BOB TO RASTA', size=28), sg.InputText(**s, k="D117")],
              [sg.Text('CAP TO BASEBALL GREY', size=28), sg.InputText(**s, k="D118")],
              [sg.Text('CAP TO ART MONSTERA', size=28), sg.InputText(**s, k="D119")],
              [sg.Text('CAP TO ART TROPICAL', size=28), sg.InputText(**s, k="D120")],
              [sg.Text('CAP TO MONSTERA GOLD', size=28), sg.InputText(**s, k="D121")],
              [sg.Text('CAP TO INSTALL', size=28), sg.InputText(**s, k="D122")],
              [sg.Text('CAP IVD HIBISANANAS', size=28), sg.InputText(**s, k="D291")],
              [sg.Text('CAP VT ICE GREEN', size=28), sg.InputText(**s, k="D292")],
              [sg.Text('CAP VT PARADISE POP', size=28), sg.InputText(**s, k="D293")],
              [sg.Text('CAP VT PAREU APE', size=28), sg.InputText(**s, k="D294")],
              [sg.Text('CAP VT PARADISE', size=28), sg.InputText(**s, k="D295")],
              [sg.Text('CASQUETTE TO JUTE', size=28), sg.InputText(**s, k="D296")]]

layout_sws = [[sg.Text('TAILLES', **c), sg.Text('S', size=4, justification="center"),
               sg.Text('M', size=4, justification="center"),
               sg.Text('L', size=4, justification="center"), sg.Text('XL', **s, justification="center"),
               sg.Text('2XL', **s, justification="center")],
              [sg.Text('SWS TO ART TROPICAL', size=28), sg.InputText(**s, k="D62"),
               sg.InputText(**s, k="D63"), sg.InputText(**s, k="D64"),
               sg.InputText(**s, k="D65"), sg.InputText(**s, k="D66")],
              [sg.Text('SWS IVD MAPE', size=28), sg.InputText(size=5, k="D67"),
               sg.InputText(**s, k="D68"), sg.InputText(**s, k="D69"),
               sg.InputText(**s, k="D70"), sg.InputText(**s, k="D71")],
              [sg.Text('SWS IVD PEOPLE', size=28), sg.InputText(**s, k="D149"),
               sg.InputText(**s, k="D150"), sg.InputText(**s, k="D151"),
               sg.InputText(**s, k="D152"), sg.InputText(**s, k="D153")]]
